#!/bin/sh
# set up symlinks to lib folders if they don't exist, on each git pull

GIT_ROOT="$(git rev-parse --show-toplevel)"
if [ ! -d "App/Lib" ]; then
  if [ "$OSTYPE" == "msys" ] || [ "$OSTYPE" == "win32" ] ; then
    cmd <<< "mklink /D \"$GIT_ROOT/App/Lib\" \"$GIT_ROOT/Lib\""
  echo 'Hello Windows';
  else
    ln -s $GIT_ROOT/Lib $GIT_ROOT/App/Lib
    echo 'Hello Unix';
  fi
fi